using JCS.Application.DTOs;

namespace JCS.Application.Interfaces.Services;

public interface IEventService { Task<EventDto?> GetByIdAsync(Guid id, CancellationToken token = default); Task<IReadOnlyCollection<EventDto>> GetAllAsync(CancellationToken token = default); Task<EventDto> CreateAsync(CreateEventDto dto, CancellationToken token = default); Task<EventDto?> UpdateAsync(Guid id, UpdateEventDto dto, CancellationToken token = default); Task<bool> DeleteAsync(Guid id, CancellationToken token = default); }
public interface IParticipantService { Task<ParticipantDto?> GetByIdAsync(Guid id, CancellationToken token = default); Task<IReadOnlyCollection<ParticipantDto>> GetAllAsync(CancellationToken token = default); Task<ParticipantDto> CreateAsync(CreateParticipantDto dto, CancellationToken token = default); Task<ParticipantDto?> UpdateAsync(Guid id, UpdateParticipantDto dto, CancellationToken token = default); Task<bool> DeleteAsync(Guid id, CancellationToken token = default); }
public interface ICertificateService { Task<CertificateDto?> GetByIdAsync(Guid id, CancellationToken token = default); Task<IReadOnlyCollection<CertificateDto>> GetAllAsync(CancellationToken token = default); Task<CertificateDto> CreateAsync(CreateCertificateDto dto, CancellationToken token = default); Task<CertificateDto?> UpdateAsync(Guid id, UpdateCertificateDto dto, CancellationToken token = default); Task<bool> DeleteAsync(Guid id, CancellationToken token = default); }
public interface ICertificateTemplateService { Task<CertificateTemplateDto?> GetByIdAsync(Guid id, CancellationToken token = default); Task<IReadOnlyCollection<CertificateTemplateDto>> GetAllAsync(CancellationToken token = default); Task<CertificateTemplateDto> CreateAsync(CreateCertificateTemplateDto dto, CancellationToken token = default); Task<CertificateTemplateDto?> UpdateAsync(Guid id, UpdateCertificateTemplateDto dto, CancellationToken token = default); Task<bool> DeleteAsync(Guid id, CancellationToken token = default); }
public interface IAuditLogService { Task<AuditLogDto?> GetByIdAsync(Guid id, CancellationToken token = default); Task<IReadOnlyCollection<AuditLogDto>> GetAllAsync(CancellationToken token = default); Task<AuditLogDto> CreateAsync(CreateAuditLogDto dto, CancellationToken token = default); }
