import {
  User,
  JamaatMember,
  Event,
  Participant,
  CertificateTemplate,
  Certificate,
  AuditLog,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    memberId: 'JMT-00101',
    fullName: 'Maulana Hafiz Tariq',
    email: 'tariq.admin@jamaat.org',
    role: 'SUPER_ADMIN',
    dila: 'National Headquarters',
    jamaat: 'Baitul Futuh',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-2',
    memberId: 'MK-10293',
    fullName: 'Abdur Raob Akhryemi',
    email: 'sadr@khuddam.ng',
    role: 'GENERAL_ADMIN',
    assignedAuxiliary: 'Khuddam',
    dila: 'Lagos Dilla',
    jamaat: 'Ojokoro',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-3',
    memberId: 'ATF-60201',
    fullName: 'Bilal Farooq',
    email: 'atfal.sec@atfal.ng',
    role: 'GENERAL_ADMIN',
    assignedAuxiliary: 'Atfal',
    dila: 'Ogun Dilla',
    jamaat: 'Abeokuta',
  },
  {
    id: 'usr-4',
    memberId: 'LAJ-40912',
    fullName: 'Amatul Noor Khan',
    email: 'amatul.noor@lajna.org',
    role: 'GENERAL_ADMIN',
    assignedAuxiliary: 'Lajna',
    dila: 'Oyo Dilla',
    jamaat: 'Ibadan',
  },
  {
    id: 'usr-5',
    memberId: 'ANS-30112',
    fullName: 'Dr. Munir Ahmad Zafar',
    email: 'munir.zafar@ansar.org',
    role: 'GENERAL_ADMIN',
    assignedAuxiliary: 'Ansarullah',
    dila: 'Abuja Dilla',
    jamaat: 'Gwarinpa',
  },
];

export const JAMAAT_MEMBER_DATABASE: JamaatMember[] = [
  {
    memberId: 'ATF-2025-01',
    fullName: 'Kabeer Olasunkanmi',
    auxiliary: 'Atfal',
    mulkOrDistrict: 'Nigeria',
    ilaqa: 'South West',
    dila: 'Lagos',
    jamaat: 'Ilasamaja',
    status: 'Active',
  },
  {
    memberId: 'ATF-2025-02',
    fullName: 'Luqman Akinwale',
    auxiliary: 'Atfal',
    mulkOrDistrict: 'Nigeria',
    ilaqa: 'South West',
    dila: 'Ogun',
    jamaat: 'Sagamu',
    status: 'Active',
  },
  {
    memberId: 'ATF-2025-03',
    fullName: 'Farooq Adeyemi',
    auxiliary: 'Atfal',
    mulkOrDistrict: 'Nigeria',
    ilaqa: 'Oyo',
    dila: 'Ibadan North',
    jamaat: 'Monatan',
    status: 'Active',
  },
  {
    memberId: 'ATF-2025-04',
    fullName: 'Habeebullahi Bello',
    auxiliary: 'Atfal',
    mulkOrDistrict: 'Nigeria',
    ilaqa: 'Lagos',
    dila: 'Lagos Mainland',
    jamaat: 'Yaba',
    status: 'Active',
  },
  {
    memberId: 'MK-10293',
    fullName: 'Abdur Raob Akhryemi',
    auxiliary: 'Khuddam',
    mulkOrDistrict: 'Nigeria',
    ilaqa: 'Lagos',
    dila: 'Lagos State',
    jamaat: 'Ojokoro',
    status: 'Active',
  },
  {
    memberId: 'MK-88201',
    fullName: 'Nabeel Tahir',
    auxiliary: 'Khuddam',
    mulkOrDistrict: 'Nigeria',
    ilaqa: 'Osun',
    dila: 'Osogbo',
    jamaat: 'Ayetoro',
    status: 'Active',
  },
  {
    memberId: 'LAJ-40912',
    fullName: 'Amatul Noor Khan',
    auxiliary: 'Lajna',
    mulkOrDistrict: 'District West',
    dila: 'Lagos Island',
    jamaat: 'Lagos Central',
    status: 'Active',
  },
];

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'evt-201',
    name: 'Islamic Vacation Course / Regional Ijtema 2025',
    description: 'A week-long spiritual education camp for Atfal focusing on Islamic morals, Quran recitation, and nation building.',
    eventType: 'Ijtema',
    date: '2025-08-03',
    endDate: '2025-08-10',
    venue: 'Jamia Ahmadiyya Ilaro, Ogun State',
    auxiliary: 'Atfal',
    orgLevel: 'Ilaqa',
    orgUnitName: 'Western Region',
    status: 'Completed',
    createdAt: '2025-07-15T10:00:00Z',
    createdBy: 'Bilal Farooq',
    participantsCount: 4,
    verifiedCount: 4,
    certificatesIssuedCount: 2,
    theme: 'My Faith, My Identity',
  },
  {
    id: 'evt-202',
    name: 'National Khuddam Annual Ijtema 2026',
    description: 'National gathering of Ahmadiyya Muslim Youth featuring academic, physical, and intellectual competitions.',
    eventType: 'Ijtema',
    date: '2026-09-18',
    endDate: '2026-09-20',
    venue: 'National Conference Grounds',
    auxiliary: 'Khuddam',
    orgLevel: 'Mulk',
    orgUnitName: 'National',
    status: 'Upcoming',
    createdAt: '2026-08-01T12:00:00Z',
    createdBy: 'Abdur Raob Akhryemi',
    participantsCount: 2,
    verifiedCount: 2,
    certificatesIssuedCount: 0,
    theme: 'Servants of the Living Faith',
  },
  {
    id: 'evt-203',
    name: 'Lajna National Tarbiyyat & Quran Seminar',
    description: 'Spiritual discourses and practical Tarbiyyat workshops for women and girls.',
    eventType: 'Seminar',
    date: '2026-10-15',
    venue: 'Baitur-Raheem Mosque',
    auxiliary: 'Lajna',
    orgLevel: 'District',
    orgUnitName: 'District South',
    status: 'Upcoming',
    createdAt: '2026-08-20T09:00:00Z',
    createdBy: 'Amatul Noor Khan',
    participantsCount: 1,
    verifiedCount: 1,
    certificatesIssuedCount: 0,
  },
];

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'part-1',
    eventId: 'evt-201',
    memberId: 'ATF-2025-01',
    fullName: 'Kabeer Olasunkanmi',
    auxiliary: 'Atfal',
    dila: 'Lagos',
    ilaqa: 'South West',
    jamaat: 'Ilasamaja',
    verificationStatus: 'Verified',
    verificationDetails: 'Active member validated in Central Jamaat Registry',
    certificateAssigned: 'Certificate of Participation',
    certificateId: 'cert-201-1',
    addedAt: '2025-08-04T10:00:00Z',
  },
  {
    id: 'part-2',
    eventId: 'evt-201',
    memberId: 'ATF-2025-02',
    fullName: 'Luqman Akinwale',
    auxiliary: 'Atfal',
    dila: 'Ogun',
    ilaqa: 'South West',
    jamaat: 'Sagamu',
    verificationStatus: 'Verified',
    verificationDetails: 'Active member validated in Central Jamaat Registry',
    certificateAssigned: 'Certificate of Participation',
    certificateId: 'cert-201-2',
    addedAt: '2025-08-04T10:05:00Z',
  },
  {
    id: 'part-3',
    eventId: 'evt-201',
    memberId: 'ATF-2025-03',
    fullName: 'Farooq Adeyemi',
    auxiliary: 'Atfal',
    dila: 'Ibadan North',
    ilaqa: 'Oyo',
    jamaat: 'Monatan',
    verificationStatus: 'Verified',
    verificationDetails: 'Active member validated in Central Jamaat Registry',
    addedAt: '2025-08-04T10:10:00Z',
  },
  {
    id: 'part-4',
    eventId: 'evt-201',
    memberId: 'ATF-2025-04',
    fullName: 'Habeebullahi Bello',
    auxiliary: 'Atfal',
    dila: 'Lagos Mainland',
    ilaqa: 'Lagos',
    jamaat: 'Yaba',
    verificationStatus: 'Verified',
    verificationDetails: 'Active member validated in Central Jamaat Registry',
    addedAt: '2025-08-04T10:15:00Z',
  },
];

// The Primary Template perfectly reflecting the user's uploaded image!
export const INITIAL_TEMPLATES: CertificateTemplate[] = [
  {
    id: 'tmpl-nigeria-atfal',
    name: 'Atfal Islamic Vacation Course (Official Green)',
    auxiliary: 'Atfal',
    certificateType: 'Certificate of Participation',
    orientation: 'landscape',
    primaryColor: '#15803d', // Vibrant green torus and badge
    accentColor: '#84cc16',  // Lime highlight and gold-green gradient
    neutralColor: '#0f172a', // Dark charcoal text
    backgroundColor: '#ffffff',
    showWaveWatermark: true,
    showTorusRings: true,
    showRosetteBadge: true,
    organizationName: 'MAJLIS ATFAL-UL AHMADIYYA NIGERIA',
    organizationSubtitle: '(Ahmadiyya Muslims Children Organization)',
    logoType: 'atfal-emblem',
    eventTitle: 'ISLAMIC VACATION COURSE/REGIONAL IJTEMA 2025',
    typeBadgeText: 'CERTIFICATE OF PARTICIPATION',
    themeTitle: 'Theme: My Faith, My Identity.',
    programDurationText: '3rd August to Sunday 10th August, 2025',
    bodyIntroText: 'This is to congratulate and certify that Tifl {{ParticipantName}}, Dilla {{Dilla}}, Ilaqa {{Ilaqa}} from {{Jamaat}}.',
    bodyDescriptionText: 'Participated in a week Islamic Vacation Course which took place at {{Venue}} from 3rd August to Sunday 10th August, 2025.',
    bodyFocusText: 'The program focussed on enhancing Islamic knowledge, promoting religious tolerance, and fostering nation-building by raising children who will contribute to peace and societal growth.',
    signature1Name: 'Abdur Raob Akhryemi',
    signature1Title: 'Sadr Majlis Khuddamul Ahmadiyya Nigeria',
    signature1Date: '10th August, 2025',
    isDefault: true,
    updatedAt: '2025-08-10T12:00:00Z',
  },
  {
    id: 'tmpl-khuddam-royal',
    name: 'Khuddam Royal Emerald & Gold',
    auxiliary: 'Khuddam',
    certificateType: 'Certificate of Excellence',
    orientation: 'landscape',
    primaryColor: '#046a38',
    accentColor: '#d97706',
    neutralColor: '#0f172a',
    backgroundColor: '#fcfdfb',
    showWaveWatermark: true,
    showTorusRings: true,
    showRosetteBadge: true,
    organizationName: 'MAJLIS KHUDDAM-UL-AHMADIYYA',
    organizationSubtitle: '(Ahmadiyya Muslim Youth Association)',
    logoType: 'khuddam-emblem',
    eventTitle: 'ANNUAL NATIONAL IJTEMA COMPETITION 2026',
    typeBadgeText: 'CERTIFICATE OF EXCELLENCE',
    themeTitle: 'Theme: Honor Thy Pledge',
    programDurationText: '18th to 20th September, 2026',
    bodyIntroText: 'Awarded with high distinction to Khadim {{ParticipantName}}, Dilla {{Dilla}}, representing {{Jamaat}} Jama\'at.',
    bodyDescriptionText: 'For securing exceptional academic merit and outstanding commitment during the National Ijtema at {{Venue}}.',
    bodyFocusText: 'In recognition of steadfast dedication to moral excellence, discipline, and selfless service to faith and nation.',
    signature1Name: 'National Sadr',
    signature1Title: 'Majlis Khuddam-ul-Ahmadiyya',
    signature1Date: '20th September, 2026',
    isDefault: false,
    updatedAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'tmpl-lajna-regal',
    name: 'Lajna Floral Regal Teal & Gold',
    auxiliary: 'Lajna',
    certificateType: 'Certificate of Appreciation',
    orientation: 'landscape',
    primaryColor: '#0f766e', // Deep Teal
    accentColor: '#f59e0b', // Amber
    neutralColor: '#0f172a',
    backgroundColor: '#fafcfb',
    showWaveWatermark: true,
    showTorusRings: true,
    showRosetteBadge: true,
    organizationName: 'LAJNA IMA\'ILLAH',
    organizationSubtitle: '(Ahmadiyya Muslim Women\'s Association)',
    logoType: 'lajna-emblem',
    eventTitle: 'NATIONAL TARBIYYAT & ACADEMIC SEMINAR 2026',
    typeBadgeText: 'CERTIFICATE OF APPRECIATION',
    themeTitle: 'Theme: Women as Pillars of Peace',
    programDurationText: '15th October, 2026',
    bodyIntroText: 'Warmly presented to Lajna member {{ParticipantName}}, Dilla {{Dilla}}, {{Jamaat}} Jama\'at.',
    bodyDescriptionText: 'In gracious appreciation for her active participation and presentation at {{Venue}}.',
    bodyFocusText: 'Exemplifying virtue, spiritual leadership, and devotion in educating future generations.',
    signature1Name: 'Sadr Lajna Ima\'illah',
    signature1Title: 'National President',
    signature1Date: '15th October, 2026',
    isDefault: false,
    updatedAt: '2026-08-15T12:00:00Z',
  },
  {
    id: 'tmpl-ansarullah-navy',
    name: 'Ansarullah Navy & Gold (Official)',
    auxiliary: 'Ansarullah',
    certificateType: 'Certificate of Recognition',
    orientation: 'landscape',
    primaryColor: '#1e3a8a', // Deep Navy Blue
    accentColor: '#d97706', // Rich Gold
    neutralColor: '#0f172a',
    backgroundColor: '#eff6ff', // Soft Blue-White
    showWaveWatermark: true,
    showTorusRings: true,
    showRosetteBadge: true,
    organizationName: 'MAJLIS ANSARULLAH NIGERIA',
    organizationSubtitle: '(Ahmadiyya Muslim Elders Association)',
    logoType: 'ansarullah-emblem',
    eventTitle: 'NATIONAL IJTEMA & TARBIYYAT CONVENTION 2026',
    typeBadgeText: 'CERTIFICATE OF RECOGNITION',
    themeTitle: 'Theme: Steadfast Servants of Allah',
    programDurationText: '22nd to 24th November, 2026',
    bodyIntroText: 'This is to proudly certify and honour Nasir {{ParticipantName}}, Dilla {{Dilla}}, Ilaqa {{Ilaqa}}, from {{Jamaat}} Jama\'at.',
    bodyDescriptionText: 'For his distinguished participation in the National Ijtema & Tarbiyyat Convention held at {{Venue}}.',
    bodyFocusText: 'A gathering dedicated to upholding the highest ideals of service, wisdom, and unwavering faith in Ahmadiyyat — for the glory of Islam and the service of humanity.',
    signature1Name: 'Sadr Majlis Ansarullah Nigeria',
    signature1Title: 'National President, Ansarullah Nigeria',
    signature1Date: '24th November, 2026',
    isDefault: false,
    updatedAt: '2026-08-20T12:00:00Z',
  },
  {
    id: 'tmpl-nasra-purple',
    name: 'Nasra Royal Purple & Silver (Official)',
    auxiliary: 'Nasra',
    certificateType: 'Certificate of Merit',
    orientation: 'landscape',
    primaryColor: '#6d28d9', // Deep Purple / Violet
    accentColor: '#a78bfa', // Soft Lavender Accent
    neutralColor: '#1e1b4b',
    backgroundColor: '#faf5ff', // Light Lavender White
    showWaveWatermark: true,
    showTorusRings: true,
    showRosetteBadge: true,
    organizationName: 'MAJLIS NASRA-TUL-AHMADIYYA NIGERIA',
    organizationSubtitle: '(Ahmadiyya Muslim Boys\' Association)',
    logoType: 'nasra-emblem',
    eventTitle: 'NATIONAL NASRA IJTEMA & SKILLS EXPOSITION 2026',
    typeBadgeText: 'CERTIFICATE OF MERIT',
    themeTitle: 'Theme: Young Minds, Strong Iman',
    programDurationText: '8th to 10th December, 2026',
    bodyIntroText: 'This is to commend and certify Nasirah {{ParticipantName}}, Dilla {{Dilla}}, Ilaqa {{Ilaqa}}, from {{Jamaat}} Jama\'at.',
    bodyDescriptionText: 'For commendable participation and dedication displayed at the National Nasra Ijtema held at {{Venue}}.',
    bodyFocusText: 'Championing youth excellence, spiritual growth, and practical service — building a generation of young Ahmadi men rooted in faith and prepared to serve the nation.',
    signature1Name: 'Sadr Majlis Nasra-tul-Ahmadiyya',
    signature1Title: 'National President, Nasra Nigeria',
    signature1Date: '10th December, 2026',
    isDefault: false,
    updatedAt: '2026-09-01T12:00:00Z',
  },
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-201-1',
    certificateNumber: 'JCS-ATF-2025-0001',
    eventId: 'evt-201',
    eventName: 'Islamic Vacation Course / Regional Ijtema 2025',
    eventDate: '3rd - 10th August, 2025',
    venue: 'Jamia Ahmadiyya Ilaro, Ogun State',
    theme: 'My Faith, My Identity',
    participantId: 'part-1',
    participantName: 'Kabeer Olasunkanmi',
    memberId: 'ATF-2025-01',
    auxiliary: 'Atfal',
    dila: 'Lagos',
    ilaqa: 'South West',
    jamaat: 'Ilasamaja',
    type: 'Certificate of Participation',
    templateId: 'tmpl-nigeria-atfal',
    issuedAt: '2025-08-10T14:00:00Z',
    issuedBy: 'Abdur Raob Akhryemi',
    status: 'Issued',
    verificationHash: '9a8b7c6d5e4f',
  },
  {
    id: 'cert-201-2',
    certificateNumber: 'JCS-ATF-2025-0002',
    eventId: 'evt-201',
    eventName: 'Islamic Vacation Course / Regional Ijtema 2025',
    eventDate: '3rd - 10th August, 2025',
    venue: 'Jamia Ahmadiyya Ilaro, Ogun State',
    theme: 'My Faith, My Identity',
    participantId: 'part-2',
    participantName: 'Luqman Akinwale',
    memberId: 'ATF-2025-02',
    auxiliary: 'Atfal',
    dila: 'Ogun',
    ilaqa: 'South West',
    jamaat: 'Sagamu',
    type: 'Certificate of Participation',
    templateId: 'tmpl-nigeria-atfal',
    issuedAt: '2025-08-10T14:05:00Z',
    issuedBy: 'Abdur Raob Akhryemi',
    status: 'Issued',
    verificationHash: '1b2c3d4e5f6a',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2025-08-10T14:05:00Z',
    action: 'Certificate Generated',
    adminName: 'Abdur Raob Akhryemi',
    adminRole: 'GENERAL_ADMIN',
    auxiliary: 'Atfal',
    target: 'Batch of 2 Certificates (IVC 2025)',
    details: 'Generated certificates JCS-ATF-2025-0001 and 0002 with theme "My Faith, My Identity".',
    ipAddress: '197.210.54.21',
  },
  {
    id: 'log-2',
    timestamp: '2025-08-04T10:15:00Z',
    action: 'Member Verification',
    adminName: 'Bilal Farooq',
    adminRole: 'GENERAL_ADMIN',
    auxiliary: 'Atfal',
    target: '4 Participants for IVC / Regional Ijtema 2025',
    details: 'Verified 4 Member IDs via Central Jamaat API: 4 Valid, 0 Invalid.',
    ipAddress: '197.210.54.18',
  },
  {
    id: 'log-3',
    timestamp: '2025-07-15T10:00:00Z',
    action: 'Event Created',
    adminName: 'Bilal Farooq',
    adminRole: 'GENERAL_ADMIN',
    auxiliary: 'Atfal',
    target: 'Islamic Vacation Course / Regional Ijtema 2025',
    details: 'Created event for Western Region at Jamia Ahmadiyya Ilaro.',
    ipAddress: '197.210.54.18',
  },
];
